/// SiginSignUpPage 
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST";
export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";





